package adkagent

// ============================================================================
// MULTILINGUAL SYNONYMS & STOP WORDS for ToolRouter
// Maps domain words in 6 languages to English keywords used for scoring
// ============================================================================

// synonyms maps domain words in multiple languages to canonical English keywords.
// These are used to expand user input tokens before scoring against tool groups.
var synonyms = map[string]string{
	// ── Russian ──────────────────────────────────────────────
	"растение":     "plant",
	"растения":     "plant",
	"цветок":       "flower",
	"цветы":        "flower",
	"монстера":     "monstera",
	"кактус":       "cactus",
	"суккулент":    "succulent",
	"базилик":      "basil",
	"трава":        "herb",
	"овощ":         "vegetable",
	"овощи":        "vegetable",
	"полив":        "watering",
	"поливать":     "watering",
	"влажность":    "moisture",
	"влага":        "moisture",
	"почва":        "soil",
	"земля":        "soil",
	"свет":         "light",
	"освещение":    "light",
	"температура":  "temperature",
	"уход":         "care",
	"ухаживать":    "care",
	"сравнить":     "compare",
	"рекомендация": "recommend",
	"рекомендации": "recommend",
	"категория":    "category",
	"категории":    "category",

	"датчик":       "sensor",
	"датчики":      "sensor",
	"сенсор":       "sensor",
	"устройство":   "device",
	"устройства":   "device",
	"батарея":      "battery",
	"батарейка":    "battery",
	"заряд":        "charge",
	"зарядка":      "charge",
	"подключить":   "connect",
	"подключение":  "connect",
	"подключиться": "connect",
	"настройка":    "setup",
	"настроить":    "setup",
	"настройки":    "setup",
	"установка":    "setup",
	"прошивка":     "firmware",
	"обновление":   "firmware",
	"сеть":         "mesh",
	"меш":         "mesh",
	"топология":    "topology",
	"проблема":     "troubleshoot",
	"неисправность":"troubleshoot",
	"сломался":     "troubleshoot",
	"ремонт":       "troubleshoot",
	"оффлайн":      "offline",
	"показания":    "reading",
	"данные":       "data",

	"приложение":   "app",
	"контакт":      "contact",
	"контакты":     "contact",
	"поддержка":    "support",
	"помощь":       "help",
	"безопасность": "security",
	"конфиденциальность": "privacy",
	"шифрование":   "encryption",
	"чип":          "chip",
	"процессор":    "chip",
	"характеристики": "specs",
	"уведомление":  "notification",
	"уведомления":  "notification",
	"оповещение":   "notification",
	"бесплатно":    "free",
	"цена":         "price",
	"стоимость":    "cost",
	"функция":      "feature",
	"функции":      "feature",
	"история":      "history",
	"экспорт":      "export",
	"график":       "chart",
	"паспорт":      "passport",

	// ── German ───────────────────────────────────────────────
	"pflanze":       "plant",
	"pflanzen":      "plant",
	"blume":         "flower",
	"blumen":        "flower",
	"feuchtigkeit":  "moisture",
	"boden":         "soil",
	"bewässerung":   "watering",
	"gießen":        "watering",
	"licht":         "light",
	"temperatur":    "temperature",
	"pflege":        "care",
	"vergleichen":   "compare",
	"empfehlung":    "recommend",
	"kategorie":     "category",

	"sensor":        "sensor",
	"gerät":         "device",
	"batterie":      "battery",
	"laden":         "charge",
	"verbinden":     "connect",
	"verbindung":    "connect",
	"einrichtung":   "setup",
	"einrichten":    "setup",
	"netzwerk":      "mesh",
	"problem":       "troubleshoot",
	"fehler":        "troubleshoot",
	"messwert":      "reading",

	"anwendung":     "app",
	"kontakt":       "contact",
	"unterstützung": "support",
	"hilfe":         "help",
	"sicherheit":    "security",
	"datenschutz":   "privacy",
	"benachrichtigung": "notification",
	"kostenlos":     "free",
	"funktion":      "feature",

	// ── Spanish ──────────────────────────────────────────────
	"planta":        "plant",
	"plantas":       "plant",
	"flor":          "flower",
	"flores":        "flower",
	"humedad":       "moisture",
	"suelo":         "soil",
	"riego":         "watering",
	"regar":         "watering",
	"luz":           "light",
	"cuidado":       "care",
	"comparar":      "compare",
	"recomendación": "recommend",
	"categoría":     "category",

	"dispositivo":   "device",
	"batería":       "battery",
	"cargar":        "charge",
	"conectar":      "connect",
	"conexión":      "connect",
	"configuración": "setup",
	"configurar":    "setup",
	"red":           "mesh",
	"problema":      "troubleshoot",

	"aplicación":    "app",
	"contacto":      "contact",
	"soporte":       "support",
	"ayuda":         "help",
	"seguridad":     "security",
	"privacidad":    "privacy",
	"notificación":  "notification",
	"gratis":        "free",
	"función":       "feature",

	// ── Portuguese ───────────────────────────────────────────
	"umidade":       "moisture",
	"solo":          "soil",
	"rega":          "watering",
	"cuidados":      "care",
	"comparação":    "compare",
	"recomendação":  "recommend",

	"dispositivos":  "device",
	"bateria":       "battery",
	"carregar":      "charge",
	"conectar_pt":   "connect", // avoid collision with Spanish
	"configuração":  "setup",
	"rede":          "mesh",

	"aplicativo":    "app",
	"contato":       "contact",
	"suporte":       "support",
	"ajuda":         "help",
	"segurança":     "security",
	"notificação":   "notification",
	"gratuito":      "free",

	// ── Chinese ──────────────────────────────────────────────
	"植物":   "plant",
	"花":     "flower",
	"湿度":   "moisture",
	"土壤":   "soil",
	"浇水":   "watering",
	"光照":   "light",
	"温度":   "temperature",
	"护理":   "care",
	"比较":   "compare",
	"推荐":   "recommend",
	"分类":   "category",

	"传感器": "sensor",
	"设备":   "device",
	"电池":   "battery",
	"充电":   "charge",
	"连接":   "connect",
	"设置":   "setup",
	"网络":   "mesh",
	"故障":   "troubleshoot",

	"应用":   "app",
	"联系":   "contact",
	"支持":   "support",
	"帮助":   "help",
	"安全":   "security",
	"芯片":   "chip",
	"规格":   "specs",
	"通知":   "notification",
	"免费":   "free",
	"功能":   "feature",
	"历史":   "history",
	"导出":   "export",
}

// stopWords are common words in multiple languages that should be ignored during tokenization.
var stopWords = map[string]bool{
	// English
	"the": true, "a": true, "an": true, "is": true, "are": true,
	"was": true, "were": true, "be": true, "been": true, "being": true,
	"have": true, "has": true, "had": true, "do": true, "does": true,
	"did": true, "will": true, "would": true, "could": true, "should": true,
	"may": true, "might": true, "can": true, "to": true, "of": true,
	"in": true, "for": true, "on": true, "with": true, "at": true,
	"by": true, "from": true, "it": true, "this": true, "that": true,
	"and": true, "or": true, "but": true, "not": true, "no": true,
	"if": true, "so": true, "up": true, "about": true, "out": true,
	"my": true, "your": true, "me": true, "i": true, "you": true,
	"we": true, "they": true, "he": true, "she": true, "its": true,
	"how": true, "what": true, "when": true, "where": true, "why": true,
	"which": true, "who": true, "whom": true, "there": true,
	"just": true, "also": true, "very": true, "much": true, "new": true,
	"get": true, "got": true, "need": true, "want": true, "know": true,
	"tell": true, "show": true, "give": true, "let": true, "make": true,
	"please": true, "thanks": true, "thank": true, "hello": true, "hi": true,

	// Russian
	"я": true, "мой": true, "моя": true, "моё": true, "мои": true,
	"ты": true, "вы": true, "он": true, "она": true, "оно": true,
	"мы": true, "они": true, "это": true, "эта": true, "этот": true,
	"как": true, "что": true, "где": true, "когда": true, "почему": true,
	"какой": true, "какая": true, "какое": true, "какие": true,
	"не": true, "но": true, "и": true, "или": true, "в": true,
	"на": true, "с": true, "у": true, "к": true, "по": true,
	"за": true, "из": true, "от": true, "для": true, "до": true,
	"ли": true, "бы": true, "же": true, "ещё": true, "уже": true,
	"тут": true, "там": true, "здесь": true, "тоже": true, "также": true,
	"очень": true, "можно": true, "нужно": true, "надо": true,
	"привет": true, "здравствуйте": true, "пожалуйста": true, "спасибо": true,

	// German
	"ich": true, "du": true, "er": true, "sie": true, "es": true,
	"wir": true, "ihr": true, "mein": true, "dein": true, "sein": true,
	"wie": true, "wo": true, "wann": true, "warum": true, "wer": true,
	"ist": true, "sind": true, "hat": true, "haben": true, "werden": true,
	"mit": true, "für": true, "und": true, "oder": true, "aber": true,
	"nicht": true, "auch": true, "noch": true, "schon": true,
	"bitte": true, "danke": true, "hallo": true,

	// Spanish
	"el": true, "la": true, "los": true, "las": true, "un": true, "una": true,
	"yo": true, "tu": true, "él": true, "ella": true, "nosotros": true,
	"cómo": true, "qué": true, "dónde": true, "cuándo": true, "porqué": true,
	"con": true, "para": true, "por": true, "hola": true, "gracias": true,

	// Chinese
	"的": true, "了": true, "吗": true, "呢": true, "是": true,
	"我": true, "你": true, "他": true, "她": true, "它": true,
	"们": true, "在": true, "有": true, "和": true, "不": true,
	"这": true, "那": true, "什么": true, "怎么": true, "哪里": true,
	"请": true, "谢谢": true, "你好": true,
}

// toolParamKeywords maps tool names to their parameter enum values.
// These provide high-signal keywords for matching user intent.
var toolParamKeywords = map[string][]string{
	"get_setup_guide": {
		"overview", "unboxing", "ble_pairing", "wifi_config",
		"mesh_setup", "plant_assign", "first_reading",
	},
	"troubleshoot_device": {
		"not_connecting", "no_readings", "wrong_values",
		"offline", "led_error", "wifi_lost", "mesh_disconnect",
		"firmware_update",
		// NOTE: "battery_drain" and "app_crash" excluded — "battery"/"drain"
		// and "app"/"crash" leak into plant/support groups via substring split.
		// "battery" and "app" are already covered by group-level keywords.
	},
	"get_mesh_info": {
		"overview", "root_node", "esp_now", "topology", "range",
	},
	"get_feature_guide": {
		"plant_passport", "predictions", "notifications", "maps", "home_assistant",
	},
	"get_app_info": {
		"platforms", "languages", "tech", "license", "requirements",
	},
	"get_security_info": {
		"privacy", "encryption", "data_storage", "permissions",
	},
	"get_hardware_specs": {
		"chip", "sensor", "battery", "pins", "wireless",
	},
	"get_plants_by_category": {
		"tropical", "succulent", "herb", "vegetable", "flowering",
	},
	"recommend_plants": {
		"beginner", "edible", "tropical", "low-light", "drought-tolerant",
		"flowering", "pet-safe",
	},
}
